services:
  db:
    image: postgres:15
    container_name: miapp_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: miappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./FinancialTrackerBackEndSpringBoot
    container_name: miapp_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/miappdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  frontend:
    build: ./FinancialTrackerFrontEndAngular
    container_name: miapp_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
