[build]
  base = "FinancialTrackerFrontEndAngular"
  command = "npm run build"
  publish = "dist/financial-tracker"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_VERSION = "10.2.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 